---
Name: app
After: "*"
---
SilverStripe\Security\Member:
  extensions:
    - TeamTrack\Extensions\MemberExtension
    
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: TeamTrack\Extensions\MemberLoginFormExtension